// =========================
// GLOBAL NAME SET (DATA ONLY)
// =========================
const NAME_SET = [
  "Ahmad Fikri Bin Abu Bakar",
  "Ainaa Farah Binti Kayat",
  "Amadifilzah Binti Abindi",
  "Amirul Hasnan Bin Faridon",
  "Anitha a/p Ponnaiah",
  "Azlinda Binti Md Azhar",
  "Diren Ashok Khandar",
  "Faizah Binti Samad",
  "Faridah a/p Uda",
  "Faridah Binti Sarmin",
  "Faridah Hanim Binti Jasmon",
  "Hayati Binti Mohd Yasim",
  "Hemalatha a/p Santhiran",
  "Irwan Bin Hamzah",
  "Jamilah Binti Mohd Rashid",
  "Kartiyani a/p Balakrishnan",
  "Kayathiri a/p Nadaraja",
  "Lizamasayu Binti Idris",
  "Marina Binti Mohd Nor",
  "Mohamad Haffis Bin Azmi",
  "Mohamad Rodzi Bin Ayob",
  "Mohammad Irfan Hakimi Bin Mohd Zaini",
  "Mohd Fairus Bin Abd Aziz",
  "Mohd Fairuz Bin Barjumin",
  "Mohd Hasif Bin Abd Hamid",
  "Muhammad Adam Bin Che Mansor",
  "Muhammad Farhan Bin Zanudin",
  "Nang Liyana Binti Nek Wahid",
  "Nazirah Binti Ibrahim",
  "Nik Norsuhada Binti Ismail",
  "Nor Asmah Binti Ali Hassan",
  "Nor Azinan Binti Anjang",
  "Nor Fathihah Binti Abdul Rashid",
  "Norayu Binti Rosli",
  "Norazekin Binti Muaaz",
  "Nordie Azrai Bin Abd Wahab",
  "Noreehan Binti Abd Hamid",
  "Noreen Iwana Binti Aludin",
  "Norkasidah Binti Nordin @ Jamaludin",
  "Nur Abidah Binti Sa'adon",
  "Nur Aqila Binti Fuadi",
  "Nur Azian Binti Mohd Isa",
  "Nur Azwida Binti Amil",
  "Nur Farhana Binti Hamidon",
  "Nur Fatin Atiqah Binti Azman",
  "Nur Majidah Binti Mohd Adam",
  "Nur Suzana Binti Md Radzi",
  "Nurhazwani Binti Hamdan",
  "Nurul 'Ain Binti Aziz@Azies",
  "Nurul Atiqah Binti Rushidi",
  "Punithamalar A/P Arumugam",
  "Puteri Hamira Binti Megat Abdul Hedei",
  "Ramachandran a/l Selvaraj",
  "Samsiah Binti Said",
  "Shahida Binti Hussin",
  "Siti Aishah Binti Abdul Aziz",
  "Siti Farahliza Binti Mohamed Isa",
  "Siti Jarah Binti Husin",
  "Siti Nor Ain Binti Mohd Rashid",
  "Siti Norain Binti Idris",
  "Sree Devi A/p Lokanathan",
  "Syahida Afifah Binti Md Nor",
  "Uma Mageswary a/p Jallendran",
  "Ummi Habibah Binti Aman @Ab Rahman",
  "Vimalah a/p Velayutham",
  "Yusri Bin Abdul Talib",
  "Zuriatihza Binti Othman"
  ];

const KE_LAS2 = [
    "Amanah",
    "Bestari",
    "Cekal",
    "Dedikasi",
    "Efektif",
    "Fokus",
    "Gigih",
    "Harmoni",
    "Inovatif",
    "Jujur"
];

const KELAS_BY_TINGKATAN = {
  "1": ["Amanah","Bestari","Cekal","Dedikasi","Efektif","Fokus","Gigih","Harmoni","Inovatif","Jujur"],
  "2": ["Amanah","Bestari","Cekal","Dedikasi","Efektif","Fokus","Gigih","Harmoni","Inovatif"],
  "3": ["Amanah","Bestari","Cekal","Dedikasi","Efektif","Fokus","Gigih","Harmoni"],
  "4": ["Amanah","Bestari","Cekal","Dedikasi","Efektif","Fokus","Gigih","Harmoni"],
  "5": ["Amanah","Bestari","Cekal","Dedikasi","Efektif","Fokus","Gigih"],
};




